services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - jwt__secretKey=${SECRET_KEY}
      - jwt__issuer=${ISSUER}
      - jwt__audience=${AUDIENCE}
      - ConnectionStrings__default=server=${SERVER};port=${PORT};database=${DB};user=${DB_USER};password=${DB_PASSWORD};Persist Security Info=False; Connect Timeout=300;
      - CorsOrigins=${CORS_ORIGINS}